### Faz o teste 
GET http://localhost:5033/api/carros/

### Cadastrar carro
POST http://localhost:5033/api/carros
Content-Type: application/json

{
    "name": "Jaguar",
    "modelo": {
        "id": 1
    }
}

### Atualiza o carro
PUT http://localhost:5033/api/carros/1
Content-Type: application/json

{
    
    "name": "Jaguar F-Type"
}

### Deleta o carro
DELETE  http://localhost:5033/api/carros/2


